<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElectronNET.Core" Version="0.5.1" />
    <PackageReference Include="ElectronNET.Core.AspNet" Version="0.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BenderBuilders.Services\BenderBuilders.Services.csproj" />
  </ItemGroup>

</Project>
